- name: Create postgres data volume
  docker_volume:
    name: postgres-data
    state: present

- name: Run Database container
  docker_container:
    name: database
    image: "ktarde/tp-devops-database:latest"
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart_policy: unless-stopped
    state: started