all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa	
  children:
    prod:
      hosts:
        kylian.tarde.takima.cloud:
          ansible_host: kylian.tarde.takima.cloud
          ansible_user: admin