name: CI devops 2025
on:
  push:
    # This workflow is triggered on push to the main and develop branches
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Set up JDK 21 for building the Java application
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        # This step runs Maven to clean and verify the project
        run: mvn clean verify --file ./simple-app/pom.xml
        # Test
