name: Run Backend Tests
on:
  push:
    # This workflow is triggered on push to the main and develop branches
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Set up JDK 21 for building the Java application
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        # This step runs Maven to build and verify the project
        run: mvn clean verify --file ./simple-api/pom.xml

      - name: SonarCloud Analysis
        # This step runs SonarCloud analysis on the project
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=tp-github-actions_project -Dsonar.organization=tp-github-actions -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./simple-api/pom.xml